### ISSUE TITLE
No Wildcard certificate?

### ISSUE THREAD

**Issue by FelixGail** [BjoernPetersen/MusicBot-LSaaS#9]
> Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for 192.168.178.120.2a10228b-c5dd-401a-8a62-fb4feb26e225.instance.kiu.party. The certificate is only valid for *.2a10228b-c5dd-401a-8a62-fb4feb26e225.instance.kiu.party.
> 
>Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by BjoernPetersen** [comment]
Yeah, I didn't think that through. The IP address at the start of the domain is obviously interpreted as a new, "deeper" subdomain, and wildcard certificates are only valid for direct subdomains AFAIK. I'll just hex-encode the IP address in the domain.
